// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfuaprrtxkpehvwzixtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdWFwcnJ0eGtwZWh2d3ppeHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwOTcyODksImV4cCI6MjA1MjY3MzI4OX0.N747la9_jIqf81fqtvckraReOlvRKFeKi9ziuLptZZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);